services:
  redis:
    container_name: redis_container
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - ./docker-volumes/cache:/data
  
  mongodb:
    container_name: mongodb_container
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./docker-volumes/data:/data/db
  
  mysql:
    container_name: mysql_container
    image: mysql:8.4.3
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=jobberapp
      - MYSQL_USER=jobber
      - MYSQL_PASSWORD=jobberpass
    volumes:
      - ./docker-volumes/mysql:/var/lib/mysql
  
  postgres:
    container_name: postgres_container
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=jobberapp
      - POSTGRES_USER=jobber
      - POSTGRES_PASSWORD=jobberpass
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
  
  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:management-alpine
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./docker-volumes/rabbitmq:/var/lib/rabbitmq
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
  
  kibana:
    image: docker.elastic.co/kibana/kibana:8.12.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5602:5601"
    depends_on:
      - elasticsearch
  # notifications:
  #   container_name: notification_container
  #   build:
  #     context: "./server/2-notification-service"
  #     dockerfile: "Dockerfile"
  #   restart: always
  #   ports:
  #     - 4101:4101
  #   env_file: "./server/2-notification-service/.env"
  #   environment:
  #     - ENABLE_APM=0
  #     - NODE_ENV=development
  #     - CLIENT_URL=http://localhost:3000
  #     - RABBITMQ_ENDPOINT=amqp://admin:admin@localhost:5672/
  #     - SENDER_EMAIL=donna.christiansen@ethereal.email
  #     - SENDER_EMAIL_PASSWORD=VsT95nXTamm86VV7ba
  #     - ELASTIC_SEARCH_URL=http://elasticsearch:9200
  #     - ELASTIC_APM_SERVER_URL=http://localhost:8200
  #     - ELASTIC_APM_SECRET_TOKEN=
  #     - PORT=4101
  

  notifications:
    container_name: notification_container
    build:
      context: "./server/2-notification-service"
      dockerfile: "Dockerfile"
    restart: always
    ports:
      - 4101:4101
    env_file: "./server/2-notification-service/.env"
    environment:
      - ENABLE_APM=0
      - NODE_ENV=development
      - CLIENT_URL=http://localhost:3000
      - RABBITMQ_ENDPOINT=amqp://admin:admin@localhost:5672/
      - SENDER_EMAIL=donna.christiansen@ethereal.email
      - SENDER_EMAIL_PASSWORD=VsT95nXTamm86VV7ba
      - ELASTIC_SEARCH_URL=http://elasticsearch:9200
      - ELASTIC_APM_SERVER_URL=http://localhost:8200
      - ELASTIC_APM_SECRET_TOKEN=
      - PORT=4101

# VOLUMES SECTION MUST BE AT ROOT LEVEL (here)
volumes:
  elasticsearch_data:

# NETWORKS SECTION AT ROOT LEVEL (here)
networks:
  elastic:
    name: elastic